credentials:
  usernames:
    bcows827:
      email: gimmeyocoupons@gmail.com
      logged_in: False # Will be managed automatically
      name: Blaine Cowen
      password: abc # Will be hashed automatically
    rbriggs:
      email: rbriggs@gmail.com
      logged_in: False # Will be managed automatically
      name: Rebecca Briggs
      password: def # Will be hashed automatically
cookie:
  expiry_days: 30
  key: plokiplokiploki # Must be string
  name: session
preauthorized:
  emails:
  - melsby@gmail.com